on:
    push:
        branches:
            - master
  
  
jobs:
    build_css:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout master Git branch
              uses: actions/checkout@v2
              with:
                ref: master
                fetch-depth: 10
                submodules: true

            - name: Make destination directory for compiled CSS
              run: mkdir -vp /tmp/www.tchekda.fr/assets/css
            - name: Installing compass
              run: |
                sudo gem install sass
                sudo gem install compass
            - name: Compile CSS from SCSS files and debug
              run: |
                compass compile -e production --css-dir=/tmp/www.tchekda.fr/assets/css/
                ls -lsah /tmp/www.tchekda.fr/assets/css/
            - name: Checkout destination Git branch
              uses: actions/checkout@v2
              with:
                  ref: gh-pages
                  fetch-depth: 1
            
            - name: Move compiled CSS to path within pr-pages branch and debug
              run: |
                mv /tmp/www.tchekda.fr/assets/css assets/css/
                ls -lsah assets/
            
            - name: Add and Commit changes to pr-pages branch
              run: |
                git config --local user.email 'action@github.com'
                git config --local user.name 'GitHub Action'
                git add -f assets/css/*
                git commit -m 'Updates compiled CSS files'
            
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: gh-pages
                