on:
    push:
        branches:
            - master
  
  
jobs:
    build_css:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout master Git branch
              uses: actions/checkout@v2
              with:
                ref: master
                fetch-depth: 10
                submodules: true

            - name: Make destination directory for compiled CSS
              run: mkdir -vp /tmp/www.tchekda.fr/assets/css
            - name: Installing compass
              run: |
                gem uninstall sass
                gem uninstall compass
            - name: Compile CSS from SCSS files
              uses: gha-utilities/sass-build@v0.2.6
              with:
                source: assets/_scss/index.scss
                destination: /tmp/www.tchekda.fr/assets/css/index.css
            
            - name: Checkout destination Git branch
              uses: actions/checkout@v2
              with:
                  ref: gh-pages
                  fetch-depth: 1
            
            - name: Move compiled CSS to path within pr-pages branch
              run: mv /tmp/www.tchekda.fr/assets/css assets/
            
            - name: Add and Commit changes to pr-pages branch
              run: |
                git config --local user.email 'action@github.com'
                git config --local user.name 'GitHub Action'
                git add assets/css/*
                git commit -m 'Updates compiled CSS files'
            
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: gh-pages
                