name: Build SASS and deploy
on:
    push:
        branches:
            - master
  
  
jobs:
    build_css:
        runs-on: ubuntu-latest

        steps:
            - name: Reset gh-pages branch
              run: |
                git branch -D gh-pages
                git branch gh-pages
            - name: Checkout gh-pages Git branch
              uses: actions/checkout@v2
              with:
                ref: gh-pages
                fetch-depth: 10
                submodules: true
                persist-credentials: false
            - name: Installing compass
              run: |
                sudo gem install sass
                sudo gem install compass
            - name: Compile CSS from SCSS files and debug
              run: |
                compass compile -e production
                ls -lsah assets/css/
            - name: Add and Commit changes
              run: |
                git config --local user.email 'action@github.com'
                git config --local user.name 'GitHub Action'
                git add -f assets/css/*
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: gh-pages