name: Build SASS and deploy
on:
    push:
        branches:
            - master
  
  
jobs:
    build_css:
        runs-on: ubuntu-latest
        name: Build SASS
        steps:
            - name: Checkout master Git branch
              uses: actions/checkout@v2
              with:
                ref: master
                fetch-depth: 10
                submodules: true
                persist-credentials: false
            - name: Installing compass
              run: |
                sudo gem install sass
                sudo gem install compass
            - name: Compile CSS from SCSS files and debug
              run: |
                compass compile -e production
                ls -lsah assets/css/
            - name: Add and Commit changes
              run: |
                git config --local user.email 'action@github.com'
                git config --local user.name 'GitHub Action'
                git add -f assets/css/*
                git commit -m 'Updates compiled CSS files'
            - name: Push changes to master
              uses: ad-m/github-push-action@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: master