name: Build SASS and deploy
on:
    push:
        branches:
            - dev
  
jobs:
    build_css:
        runs-on: ubuntu-latest
        name: Build SASS
        steps:
            - name: Checkout dev Git branch
              uses: actions/checkout@v2
              with:
                ref: dev
            - name: Make destination directory for compiled project
              run: |
                mkdir -vp /tmp/project/
                cp -r ./ /tmp/project/
            - name: Installing compass
              run: |
                sudo gem install sass
                sudo gem install compass
            - name: Compile CSS from SCSS files and debug
              run: |
                compass compile -e production --css-dir=/tmp/project/assets/css
                ls -lsah /tmp/project/assets/css/
            - name: Checkout master Git branch
              uses: actions/checkout@v2
              with:
                ref: master
            - name: Load new code to master and debug
              run: |
                cp -fvr /tmp/project/* ./
                rm -rf tmp/
                rm -rf project/
                ls -lsah
            - name: Fix sourcemap
              run: sed -i 's/\/\.\.\/\.\.\/\.\.\/home\/runner\/work\/tchekda\.github\.io\/tchekda\.github\.io\/assets//g' assets/css/index.css.map
            - name: Add and Commit changes to master branch
              run: |
                git config --local user.email 'action@github.com'
                git config --local user.name 'GitHub Action'
                git add .
                git add -f assets/css/*
                git commit -m 'Updates compiled CSS files'
            - name: Push changes to master
              uses: ad-m/github-push-action@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: master
